// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	PassWord             string   `protobuf:"bytes,2,opt,name=passWord,proto3" json:"passWord,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginRequest) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

type LogoutRequest struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{1}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *LogoutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RegisterRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	PassWord             string   `protobuf:"bytes,2,opt,name=passWord,proto3" json:"passWord,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{2}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegisterRequest) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

type AuthResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{3}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AuthResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "proto.LoginRequest")
	proto.RegisterType((*LogoutRequest)(nil), "proto.LogoutRequest")
	proto.RegisterType((*RegisterRequest)(nil), "proto.RegisterRequest")
	proto.RegisterType((*AuthResponse)(nil), "proto.AuthResponse")
}

func init() { proto.RegisterFile("proto/auth.proto", fileDescriptor_a9d38a2cdbb4f144) }

var fileDescriptor_a9d38a2cdbb4f144 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x50, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x25, 0xd6, 0x48, 0x3a, 0x56, 0x2c, 0x63, 0x91, 0xd2, 0x93, 0xe4, 0xe4, 0x29, 0x05, 0x15,
	0x05, 0x3d, 0x69, 0x40, 0x50, 0x8a, 0x94, 0xbd, 0x08, 0xde, 0xa2, 0x19, 0x92, 0x20, 0xcd, 0xc4,
	0xec, 0xec, 0x9f, 0xf9, 0x81, 0xb2, 0x9b, 0xc4, 0x54, 0xc9, 0xad, 0xa7, 0x79, 0xb3, 0xb3, 0x6f,
	0xde, 0x9b, 0x07, 0xd3, 0xaa, 0x66, 0xe1, 0x65, 0x62, 0x24, 0x8f, 0x1c, 0x44, 0xdf, 0x95, 0xf0,
	0x11, 0x26, 0x2b, 0xce, 0x8a, 0x52, 0xd1, 0x97, 0x21, 0x2d, 0xb8, 0x80, 0xc0, 0x68, 0xaa, 0x5f,
	0x92, 0x0d, 0xcd, 0xbd, 0x33, 0xef, 0x7c, 0xac, 0x7e, 0x7b, 0x3b, 0xab, 0x12, 0xad, 0x5f, 0xb9,
	0x4e, 0xe7, 0x7b, 0xcd, 0xac, 0xeb, 0xc3, 0x1b, 0x38, 0x5a, 0x71, 0xc6, 0x46, 0xba, 0x45, 0x53,
	0x18, 0x99, 0x22, 0x75, 0x3b, 0x7c, 0x65, 0x21, 0xce, 0xc0, 0x17, 0xfe, 0xa4, 0xb2, 0xe5, 0x36,
	0x4d, 0xf8, 0x04, 0xc7, 0x8a, 0xb2, 0x42, 0x0b, 0xd5, 0xbb, 0x7a, 0x78, 0x86, 0xc9, 0xbd, 0x91,
	0x5c, 0x91, 0xae, 0xb8, 0xd4, 0x84, 0x08, 0xfb, 0x1f, 0x9c, 0x52, 0xeb, 0xc1, 0x61, 0x6b, 0x6b,
	0xa3, 0xb3, 0x96, 0x6a, 0x61, 0x6f, 0x6b, 0xb4, 0x65, 0xeb, 0xe2, 0xdb, 0x83, 0x20, 0xce, 0x13,
	0xb1, 0x0b, 0xf1, 0x0a, 0x02, 0xb5, 0x8e, 0x5d, 0x4e, 0x78, 0xd2, 0xe4, 0x17, 0x6d, 0xa7, 0xb6,
	0xe8, 0x1e, 0xff, 0xc8, 0xdf, 0xc2, 0xa1, 0x5a, 0xc7, 0xdd, 0x71, 0x78, 0xda, 0xfe, 0xf9, 0x77,
	0xed, 0x30, 0xf7, 0x1a, 0xc6, 0x8d, 0x22, 0x1b, 0xc1, 0x59, 0x2f, 0xd9, 0x07, 0x3c, 0xc8, 0x7b,
	0x80, 0xb7, 0x60, 0x19, 0xdd, 0xb9, 0xc1, 0xfb, 0x81, 0x2b, 0x97, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x73, 0xa8, 0xaa, 0xff, 0xfc, 0x01, 0x00, 0x00,
}
